### ISSUE TITLE
TypeError: cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index-deleter#1]
Getting this on my indexing process for my website.

``` javascript
/home/user/javascript/website/node_modules/search-index-deleter/deleter.js:82
      options.log.info(err)
                 ^

TypeError: Cannot read property 'info' of undefined
    at /home/user/javascript/website/node_modules/search-index-deleter/deleter.js:82:18
    at /home/user/javascript/website/node_modules/async/lib/async.js:52:16
    at /home/user/javascript/website/node_modules/async/lib/async.js:361:13
    at /home/user/javascript/website/node_modules/async/lib/async.js:52:16
    at replenish (/home/user/javascript/website/node_modules/async/lib/async.js:314:29)
    at /home/user/javascript/website/node_modules/async/lib/async.js:330:15
    at _asyncMap (/home/user/javascript/website/node_modules/async/lib/async.js:355:9)
    at Object.mapLimit (/home/user/javascript/website/node_modules/async/lib/async.js:342:20)
    at deleteThisBatch (/home/user/javascript/website/node_modules/search-index-deleter/deleter.js:53:5)
    at /home/user/javascript/website/node_modules/search-index-deleter/deleter.js:153:11
    at /home/user/javascript/website/node_modules/async/lib/async.js:52:16
    at /home/user/javascript/website/node_modules/async/lib/async.js:361:13
    at /home/user/javascript/website/node_modules/async/lib/async.js:52:16
    at replenish (/home/user/javascript/website/node_modules/async/lib/async.js:306:28)
    at /home/user/javascript/website/node_modules/async/lib/async.js:326:29
    at /home/user/javascript/website/node_modules/async/lib/async.js:44:16
```

Any advice on how to fix this fast? It is a bug on my `search-index` use?

I'm instancing `search-index` with this options:

``` javascript
var opts = {
    indexPath: 'search_index',
    fieldedSearch: false
  };
```

**Comment by fergiemcdowall** [comment]
For a fast fix, simply go into the code and comment out the line. The logging needs an overhaul- will fix asap

**Comment by jacargentina** [comment]
Now i'm getting similar from `search-index-adder`

**Comment by fergiemcdowall** [comment]
@jacargentina I cant reproduce that error. If you can throw together a test case then I can fix it for you

**Comment by jacargentina** [comment]
@fergiemcdowall trying to help. I'm looking at the tests, and it seems that reusing the `sandbox` makes various test to fail.

I've done this, with a clean clone from `search-index`:

``` bash
npm run test
```

All green. Then:

``` bash
npm run test-node
```

Is this behaviour normal? Shouldn't the tests work with already created indexes?

I'm not saying this is related to the exception, but i've tried that sandbox reusing as i _suspect_ my use case to reproduce the bug is to index my website; and later on a re-indexing (without deleting the index) causes the error

**Comment by fergiemcdowall** [comment]
The tests require an empty sandbox. Not due to any limitation, but simply to they can verify what is where and when.

When doing big indexing jobs, it is best to start on an empty index, or at least one that doesnt contain the IDs of the documents you are indexing, since this removes the need for deletion, and speeds things up quite a lot

**Comment by fergiemcdowall** [comment]
(because if you add a document with an ID that is already in the index, the existing doc must first be deleted before the new one is added)

**Comment by jacargentina** [comment]
The index should be usable while rebuilding it. Also, i don't think that idea should be applicable for large data sets (google? yahoo?)

I'm building a _little search engine_ for my own website; today its not very large, but on a year or so... it will be much **larger**, and the time to build the index again, will make it **really slow**.

Anyway, i will look without the tests if i can reproduce the error again.

**Comment by fergiemcdowall** [comment]
A test can be any sort of code that will reproduce the problem. You don't have to worry about the tests that are there already.

Search-index should be fine for your website in terms of performance.

**Comment by jacargentina** [comment]
I've found there are problems when trying to instance the searchIndex a second time with the same index on disk (its not possible may be?) If @fergiemcdowall you say **yes**, then close this :)

**Comment by fergiemcdowall** [comment]
If you are indexing the same dataset, then you should definitely delete the docs that are there from before, since the index will be forced to do a lot of unnecessary recalibration.
